# Module 1 - Data Pipeline

**Project:** Zepto Data & AI Platform

**Author:** Joniboyina Jeevan Venkatesh

This notebook demonstrates the complete data pipeline:
- Load SQLite database
- Execute SQL queries using pandas
- Reproduce JOIN using pandas merge
- Compare SQL JOIN and pandas merge results

In [1]:
#import Libraries
import sqlite3
import pandas as pd

In [2]:
#Connect Database
connection = sqlite3.connect("books.db")

In [3]:
#First pd.read_sql()
query = """
SELECT title, rating
FROM books
WHERE rating >= 4;
"""

high_rating_books = pd.read_sql(query, connection)

high_rating_books.head()

                                               title  rating
0                                      Sharp Objects       4
1              Sapiens: A Brief History of Humankind       5
2  The Dirty Little Secrets of Getting Your Dream...       4
3  The Boys in the Boat: Nine Americans and Their...       4
4                              Shakespeare's Sonnets       4

In [4]:
#Second pd.read_sql()
query = """
SELECT title, price_inr
FROM books
ORDER BY price_inr DESC
LIMIT 10;
"""

expensive_books = pd.read_sql(query, connection)

expensive_books

                                               title  price_inr
0       The Death of Humanity: and the Case for Life    6130.60
1                     Slow States of Collapse: Poems    6046.20
2  Our Band Could Be Your Life: Scenes from the A...    6039.88
3                                The Past Never Ends    5960.75
4  The Pioneer Woman Cooks: Dinnertime: Comfort C...    5951.25
5                                  Masks and Shadows    5950.20
6                    The Secret of Dreadwillow Carse    5921.72
7  The Electric Pencil: Drawings from Inside Stat...    5914.33
8                      Birdsong: A Story in Pictures    5764.52
9              Sapiens: A Brief History of Humankind    5721.26

In [5]:
#SQL JOIN
query = """
SELECT
books.title,
books.price_inr,
books.rating,
categories.category_name
FROM books
INNER JOIN categories
ON books.category_id = categories.category_id;
"""

sql_join = pd.read_sql(query, connection)

sql_join.head()

                                   title  price_inr  rating category_name
0                   A Light in the Attic    5461.74       3     All Books
1                     Tipping the Velvet    5669.57       1     All Books
2                             Soumission    5285.55       1     All Books
3                          Sharp Objects    5045.01       4     All Books
4  Sapiens: A Brief History of Humankind    5721.26       5     All Books

In [6]:
#Pandas Merge
books_df = pd.read_sql(
    "SELECT * FROM books;",
    connection
)

categories_df = pd.read_sql(
    "SELECT * FROM categories;",
    connection
)

merged_df = pd.merge(
    books_df,
    categories_df,
    on="category_id",
    how="inner"
)

merged_df.head()

,book_id,title,price_gbp,price_inr,rating,in_stock,category_id,category_name
0,1,A Light in the Attic,51.77,5461.74,3,1,1,All Books
1,2,Tipping the Velvet,53.74,5669.57,1,1,1,All Books
2,3,Soumission,50.10,5285.55,1,1,1,All Books
3,4,Sharp Objects,47.82,5045.01,4,1,1,All Books
4,5,Sapiens: A Brief History of Humankind,54.23,5721.26,5,1,1,All Books

In [7]:
#Compare Results
print("SQL JOIN Shape")

print(sql_join.shape)

print()

print("Pandas Merge Shape")

print(merged_df.shape)

SQL JOIN Shape
(100, 4)

Pandas Merge Shape
(100, 8)

In [8]:
#Close Database
connection.close()